### ISSUE TITLE
Support for python 2

### ISSUE THREAD

**Issue by vincecr0ft** [beojan/atlas-mpl#1]
I don't see anything in here python3 related. 

This package is really useful for making quick plots on systems where a default python version (still 2.7 in most cases) and little else. Anything I can do to help make this happen?

**Comment by beojan** [comment]
f-strings are the blocker, so it's really just drawing the ATLAS label that really needs Python 3. If that were split off into a separate file, the rest of the module could support Python 2. (I don't know how to express that in the dependencies though without splitting it into two packages which I would rather not do). 

Though for quick plots, you should note that the ATLAS style (but not the bonus ones) need a working LaTeX installation.

**Comment by beojan** [comment]
Closing old issue, particularly now that Python 2 is EOL.
