### ISSUE TITLE
Provide documentation for needed latex modules

### ISSUE THREAD

**Issue by mswiatlo** [beojan/atlas-mpl#3]
Many users will probably want to run this in Docker, where texlive-full may not be available. I spent some time trying to find a minimal set of texlive packages to get this working. It seems to be roughly: 

 texlive-latex-extra texlive-fonts-recommended texlive-science texlive-lang-greek dvipng

Is this correct? Probably it would be helpful to add to the docs, since a naive pip install is not sufficient.

**Comment by beojan** [comment]
What distro is that for?

For Debian, it looks like the list is:
- texlive
- texlive-science
- texlive-latex-extra
- tex-gyre

With Iosevka and Fira Sans needing to be installed from upstream (not needed for the ATLAS style).

For CentOS 7, it seems the distro provides TeXLive 2012 which is probably too old, so TeXLive would need to be installed from upstream.

**Comment by mswiatlo** [comment]
My docker image is based on Ubuntu bionic (18.04).

Anyway just adding a few suggestions like this will help people figure it out if one or two are still missing.

**Comment by mswiatlo** [comment]
PS Your list may be better than mine-- mine works but I didn't try every permutation.

**Comment by beojan** [comment]
I just went with the union of the two lists.
