### ISSUE TITLE
Z label?

### ISSUE THREAD

**Issue by mswiatlo** [beojan/atlas-mpl#5]
Hi, 

Another fun feature would be adding z label functions like you have for x an y. For example in this plot:

<img width="506" alt="image" src="https://user-images.githubusercontent.com/3971806/74603959-7a584b00-50b9-11ea-87cc-bbd29a63d767.png">

The z-axis should be right-aligned (so to the top of the bar)

Cheers,
Max

**Comment by beojan** [comment]
Added this. It's slightly different to the other two because the way matplotlib handles colorbars means the colorbar needs to be passed into the `set_zlabel` function.
