### ISSUE TITLE
Usage in Jupyter

### ISSUE THREAD

**Issue by jtchilders** [beojan/atlas-mpl#6]
Thank you for providing this module, though I'm not clear on how to use it properly.

I have done this:
```python
import matplotlib
import matplotlib.pyplot as plt
matplotlib.rc('text', usetex=True)
import atlas_mpl_style as ampl
ampl.use_atlas_style()
```

then I have pandas data frames I want to histogram. How should I go about that? 

I couldn't get your `plot_1d()` function working properly so I just tried `plt.hist()` which mostly works. As in, the font styles seem all set to Helvetica. However, my axis tick labels are still Times New Roman. I was able to change one axis using: 
```python
from matplotlib.font_manager import FontProperties
helveticafont = FontProperties(fname='Helvetica',style='italic',size=12)
ax.set_xticklabels(...,fontproperties=helveticafont)```
However, the y-axis is log, so it uses latex to format the exponents 10^1, 10^2, etc. This falls back to times new roman for some reason.

Any advice would be appreciated.

**Comment by beojan** [comment]
Usetex is set by `use_atlas_style`, so there's no need to do that yourself.

Everything in the plot module is designed to work with NumPy style histogram (i.e. separate arrays for bin edges, bin values, and bin errors). You can get this using `np.histogram` or (better) by using `boost_histogram` which despite the name has first-class Python bindings.

On the font issue, can you post the code you've tried and it's output? Could you also try building the test LaTeX file included so we can check you have a TeX installation with the necessary packages installed?

**Comment by beojan** [comment]
I should add though, if you've got your data in a Pandas dataframe and just want to look at the histogram (not carry out computations on it), the dataframe `hist` method is probably the easiest way to do this.

The plot module included here is geared more toward
1. Plots in notes or talks, showing backgrounds and data (or limits), and
2. Histograms read out of ROOT files, or other situations where you have a histogram already as opposed to the raw data.
