### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by filip-frisk** [beojan/atlas-mpl#8]
Thank you for the project, I just started using it and I am doing a lot of trial and error in investigating the basic functionality. Would it be possible of you to add some example code? Especially something as complex as https://atlas.web.cern.ch/Atlas/GROUPS/PHYSICS/PAPERS/SUSY-2018-06/fig_03b.png as @mswiatlo mentioned.

**Comment by beojan** [comment]
Sorry for the delay. Here's an example notebook. The output looks like this:
![image](https://github.com/beojan/atlas-mpl/assets/3727925/3933e335-54af-4a76-841c-ae4a5fc5090b)

[ATLAS MPL Style Examples.tar.gz](https://github.com/beojan/atlas-mpl/files/11807731/ATLAS.MPL.Style.Examples.tar.gz)
